name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run AI Code Reviewer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ejecuta el script directamente; no necesitas ngrok ni servidor web en CI
          node src/server.js \
            --event pull_request \
            --payload .github/ai-payload.json

      # (Opcional) Si quieres fallar el build en función de severidad:
      - name: Check for blocker issues
        if: always()
        run: |
          if grep -q '"SEVERITY": *"BLOCKER"' report.json; then
            echo "❌ Found blocker issues, failing build."
            exit 1
          fi
